builds:
  - binary: filemass
    main: ./cmd/FileMass/main.go
    goos:
      - windows
      - darwin
      - linux
      - openbsd
      - freebsd
    goarch:
      - amd64
      - arm64
    goarm:
      - 5
      - 6
      - 7
    gomips:
      - hardfloat
      - softfloat
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
      - -trimpath

archives:
  - files:
      - none*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
